#!/usr/bin/env node
// Regenerates the idea table in README.md between the IDEAS markers.
// Usage: node scripts/build-index.mjs [--check]
import fs from "node:fs";
import path from "node:path";
import { ROOT, listIdeas, STATUSES, AREAS, COMPLEXITIES } from "./lib.mjs";

const START = "<!-- IDEAS:START -->";
const END = "<!-- IDEAS:END -->";
const NOTE = "<!-- This table is generated by scripts/build-index.mjs. Do not edit by hand. -->";

const BADGE = {
  idea: "idea",
  speced: "**speced**",
  claimed: "**claimed**",
  released: "**released**",
  abandoned: "~~abandoned~~",
};

const ideas = listIdeas();
const problems = [];

for (const { file, data } of ideas) {
  const expected = `${String(data.id).padStart(4, "0")}-${data.slug}.md`;
  if (file !== expected) problems.push(`${file}: filename should be ${expected} (id/slug mismatch)`);
  if (!STATUSES.includes(data.status)) problems.push(`${file}: unknown status "${data.status}"`);
  if (data.complexity && !COMPLEXITIES.includes(data.complexity)) {
    problems.push(`${file}: unknown complexity "${data.complexity}"`);
  }
  for (const a of data.areas ?? []) {
    if (!AREAS.includes(a)) problems.push(`${file}: unknown area "${a}"`);
  }
}

const rows = ideas.map(({ file, data }) => {
  const id = String(data.id).padStart(4, "0");
  const title = `[${data.title}](ideas/${file})`;
  const areas = (data.areas ?? []).join(", ") || "—";
  const size = data.complexity ?? "—";
  const links = [
    data.issue ? `[#${data.issue}](../../issues/${data.issue})` : null,
    data.repo ? `[repo](${data.repo})` : null,
  ].filter(Boolean).join(" · ") || "—";
  return `| ${id} | ${title} | ${BADGE[data.status] ?? data.status} | ${areas} | ${size} | ${links} |`;
});

const table = ideas.length
  ? ["| # | Idea | Status | Areas | Size | Links |", "| --- | --- | --- | --- | --- | --- |", ...rows].join("\n")
  : "_Nothing here yet. [Post the first one.](../../issues/new?template=idea.yml)_";

const readmePath = path.join(ROOT, "README.md");
const readme = fs.readFileSync(readmePath, "utf8");
const s = readme.indexOf(START);
const e = readme.indexOf(END);
if (s === -1 || e === -1) {
  console.error(`README.md is missing the ${START} / ${END} markers.`);
  process.exit(1);
}

const next = `${readme.slice(0, s)}${START}\n${NOTE}\n\n${table}\n\n${readme.slice(e)}`;

if (process.argv.includes("--check")) {
  if (next !== readme) problems.push("README index is out of date - run: node scripts/build-index.mjs");
} else if (next !== readme) {
  fs.writeFileSync(readmePath, next);
  console.log(`Updated README index (${ideas.length} idea${ideas.length === 1 ? "" : "s"}).`);
} else {
  console.log(`README index already up to date (${ideas.length} idea${ideas.length === 1 ? "" : "s"}).`);
}

if (problems.length) {
  console.error("\nProblems:");
  for (const p of problems) console.error("  - " + p);
  process.exit(1);
}
